### ISSUE TITLE
上下文回复报错喔

### ISSUE THREAD

**Issue by FebruaryMaple** [Alpaca4610/nonebot-plugin-xinghuo-api#17]
上下文回复的功能第一条还可以正常回复 但是从第二条开始就会报错 清除聊天记录的功能也是这样

非上下文回复的功能完全可以正常运行

12-10 01:34:39 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_xinghuo_api, lineno=77) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
    uvicorn.run(
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\LLBOT\1208 nonebot\Maple-24-12-08\.venv\lib\site-packages\nonebot_plugin_xinghuo_api\__init__.py", line 116, in _
    session[session_id].append(ChatMessage(role="assistant", content=res))
UnboundLocalError: local variable 'res' referenced before assignment

怎么弄也没弄明白 大佬救救我😢😢😢

**Comment by LEKOULEKOUHAO** [comment]
把__init__.py文件的116行改为session[session_id].append(ChatMessage(role="user", content=content))应该就好了，前面有issue提过，你可以去看一下

**Comment by FebruaryMaple** [comment]
喔喔 还真是 改完了就好了 谢谢神医！欸嘿嘿

**Comment by Alpaca4610** [comment]
github上的代码是修改过的，一直忘了发包😂感谢提醒，我更新下pypi的包
