### ISSUE TITLE
只能看到一条回复

### ISSUE THREAD

**Issue by dngymr** [Alpaca4610/nonebot-plugin-xinghuo-api#8]
安装上后，后台看到回复了两条，但是聊天界面只看得到一条，就是“星火大模型正在思考中....”，剩下的一条应该是思考结果，但是没发出来，不知道是哪里出问题了。

**Comment by Alpaca4610** [comment]
看一下gocq里面的消息有没有成功发送出去

**Comment by dngymr** [comment]
你好你好！
是这样的，
这是go-cqhttp的后台，显示是有两条消息的，

但是界面上只有1条消息

我后来看到另一边显示的报错是这样的，

我是还有哪里代码需要改一下吗？
非常感谢！




Yu&nbsp;Gao-7714014
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alpaca4610/nonebot-plugin-xinghuo-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月12日(星期二) 上午10:57
***@***.***&gt;;
抄送:&nbsp;"Yu ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alpaca4610/nonebot-plugin-xinghuo-api] 只能看到一条回复 (Issue #8)





 
看一下gocq里面的消息有没有成功发送出去

**Comment by Alpaca4610** [comment]
报错信息请再发一下，我这边好像没看到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月12日(周二) 上午9:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Alpaca4610/nonebot-plugin-xinghuo-api] 只能看到一条回复 (Issue #8)




 
安装上后，后台看到回复了两条，但是聊天界面只看得到一条，就是“星火大模型正在思考中....”，剩下的一条应该是思考结果，但是没发出来，不知道是哪里出问题了。

**Comment by Alpaca4610** [comment]
对于群聊的报错，你试一下在配置文件中设置xinghuo_api_version的值为v3
对于私聊的报错，好像是是gocq的API的问题，明天我有空看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月12日(周二) 晚上11:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Alpaca4610/nonebot-plugin-xinghuo-api] 只能看到一条回复 (Issue #8)




 您好！首先非常感您愿意帮助我！ 
 然后是这样的， 
 私聊的时候报错如下： 
 12-12 23:46:19 [SUCCESS] nonebot | OneBot V11 123456789 | [message.group.normal]: Message -1724157668 from 3452087212@[群:728038120] '/xh 请用10个字介绍一下牡丹花' 
 12-12 23:46:19 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.nonebot_plugin_xinghuo_api, lineno=55) 
 12-12 23:46:24 [INFO] nonebot | Matcher(type='message', module=src.plugins.nonebot_plugin_xinghuo_api, lineno=55) running complete 
 12-12 23:46:24 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_xinghuo_api, lineno=55) failed. 
 Traceback (most recent call last): 
 &amp;nbsp; File "f:\python_install\lib\runpy.py", line 194, in _run_module_as_main 
 &amp;nbsp; &amp;nbsp; return _run_code(code, main_globals, None, 
 &amp;nbsp; File "f:\python_install\lib\runpy.py", line 87, in _run_code 
 &amp;nbsp; &amp;nbsp; exec(code, run_globals) 
 &amp;nbsp; File "F:\Python_install\Scripts\nb.exe\__main__.py", line 7, in <module&amp;gt; 
 &amp;nbsp; &amp;nbsp; sys.exit(main()) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\click\core.py", line 1130, in __call__ 
 &amp;nbsp; &amp;nbsp; return self.main(*args, **kwargs) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\click\core.py", line 1055, in main 
 &amp;nbsp; &amp;nbsp; rv = self.invoke(ctx) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\click\core.py", line 1657, in invoke 
 &amp;nbsp; &amp;nbsp; return _process_result(sub_ctx.command.invoke(sub_ctx)) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\click\core.py", line 1404, in invoke 
 &amp;nbsp; &amp;nbsp; return ctx.invoke(self.callback, **ctx.params) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\click\core.py", line 760, in invoke 
 &amp;nbsp; &amp;nbsp; return __callback(*args, **kwargs) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nb_cli\commands\main.py", line 30, in run 
 &amp;nbsp; &amp;nbsp; run_bot(file, app) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot 
 &amp;nbsp; &amp;nbsp; nonebot.run(app=f"{module_name}:{app}") 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\__init__.py", line 331, in run 
 &amp;nbsp; &amp;nbsp; get_driver().run(*args, **kwargs) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run 
 &amp;nbsp; &amp;nbsp; uvicorn.run( 
 &amp;nbsp; File "f:\python_install\lib\site-packages\uvicorn\main.py", line 576, in run 
 &amp;nbsp; &amp;nbsp; server.run() 
 &amp;nbsp; File "f:\python_install\lib\site-packages\uvicorn\server.py", line 60, in run 
 &amp;nbsp; &amp;nbsp; return asyncio.run(self.serve(sockets=sockets)) 
 &amp;nbsp; File "f:\python_install\lib\asyncio\runners.py", line 43, in run 
 &amp;nbsp; &amp;nbsp; return loop.run_until_complete(main) 
 &amp;nbsp; File "f:\python_install\lib\asyncio\base_events.py", line 603, in run_until_complete 
 &amp;nbsp; &amp;nbsp; self.run_forever() 
 &amp;nbsp; File "f:\python_install\lib\asyncio\windows_events.py", line 316, in run_forever 
 &amp;nbsp; &amp;nbsp; super().run_forever() 
 &amp;nbsp; File "f:\python_install\lib\asyncio\base_events.py", line 570, in run_forever 
 &amp;nbsp; &amp;nbsp; self._run_once() 
 &amp;nbsp; File "f:\python_install\lib\asyncio\base_events.py", line 1859, in _run_once 
 &amp;nbsp; &amp;nbsp; handle._run() 
 &amp;nbsp; File "f:\python_install\lib\asyncio\events.py", line 81, in _run 
 &amp;nbsp; &amp;nbsp; self._context.run(self._callback, *self._args) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher 
 &amp;nbsp; &amp;nbsp; await _run_matcher( 
 &amp;gt; File "f:\python_install\lib\site-packages\nonebot\message.py", line 428, in _run_matcher 
 &amp;nbsp; &amp;nbsp; await matcher.run(bot, event, state, stack, dependency_cache) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run 
 &amp;nbsp; &amp;nbsp; await self.simple_run(bot, event, state, stack, dependency_cache) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run 
 &amp;nbsp; &amp;nbsp; await handler( 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__ 
 &amp;nbsp; &amp;nbsp; return await cast(Callable[..., Awaitable[R]], self.call)(**values) 
 &amp;nbsp; File ".\src\plugins\nonebot_plugin_xinghuo_api\__init__.py", line 80, in _ 
 &amp;nbsp; &amp;nbsp; await chat_record.send(MessageSegment.text("星火大模型正在思考中......")) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\internal\matcher\matcher.py", line 554, in send 
 &amp;nbsp; &amp;nbsp; return await bot.send(event=event, message=_message, **kwargs) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 225, in send 
 &amp;nbsp; &amp;nbsp; return await self.__class__.send_handler(self, event, message, **kwargs) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 178, in send 
 &amp;nbsp; &amp;nbsp; return await bot.send_msg(**params) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\internal\adapter\bot.py", line 123, in call_api 
 &amp;nbsp; &amp;nbsp; raise exception 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api 
 &amp;nbsp; &amp;nbsp; result = await self.adapter._call_api(self, api, **data) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 144, in _call_api 
 &amp;nbsp; &amp;nbsp; return handle_api_result(await self._result_store.fetch(seq, timeout)) 
 &amp;nbsp; File "f:\python_install\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result 
 &amp;nbsp; &amp;nbsp; raise ActionFailed(**result) 
 nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='1', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出') 
 
 
 
 go-cqhttp显示发送了两个消息 
 
 但实际上只看到了1个消息 
 
 
 
 
 
 群聊的报错如下 
 12-12 23:46:47 [SUCCESS] nonebot | OneBot V11 123456789 | [message.private.friend]: Message -1429798194 from 3452087212 '/xh 请用10个字介绍一下牡丹花' 
 12-12 23:46:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.chatmessage, lineno=17) 
 12-12 23:46:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.private_chatmessage, lineno=17) 
 12-12 23:46:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.chat, lineno=17) 
 12-12 23:46:47 [INFO] nonebot | Matcher(type='message', module=src.plugins.chatmessage, lineno=17) running complete 
 12-12 23:46:47 [INFO] nonebot | Matcher(type='message', module=src.plugins.chat, lineno=17) running complete 
 12-12 23:46:47 [INFO] nonebot | Matcher(type='message', module=src.plugins.private_chatmessage, lineno=17) running complete 
 12-12 23:46:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.nonebot_plugin_xinghuo_api, lineno=55) 
 请求错误: 10005, {'header': {'code': 10005, 'message': 'InvalidParamError:(23:46:47.643) get assistant info error:cbm api code 10404, error data not found', 'sid': ***@***.***', 'status': 2}} 
 
 
 
 go-cqhttp里直接说发送失败，但其实没有被风控 
 
 聊天界面也没有回复。 
 
 
 插件的代码我没有改，只不过配置的时候用的v3。 
 非常感谢您的宝贵时间！ 
 
 
 Yu&amp;nbsp;Gao-7714014 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Alpaca4610/nonebot-plugin-xinghuo-api"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年12月12日(星期二) 晚上11:19 
 ***@***.***&amp;gt;; 
 抄送:&amp;nbsp;"Yu ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Alpaca4610/nonebot-plugin-xinghuo-api] 只能看到一条回复 (Issue #8) 
 
 
 
 
 
  报错信息请再发一下，我这边好像没看到  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年12月12日(周二) 上午9:52  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: [Alpaca4610/nonebot-plugin-xinghuo-api] 只能看到一条回复 (Issue #8)  
   
   
   
   
     
  安装上后，后台看到回复了两条，但是聊天界面只看得到一条，就是“星火大模型正在思考中....”，剩下的一条应该是思考结果，但是没发出来，不知道是哪里出问题了。

**Comment by Alpaca4610** [comment]
https://github.com/Alpaca4610/nonebot-plugin-xinghuo-api/issues/10
